--[[
	This is a XenoBot example script, intended to
	teach new users about the scripting API and 
	act as script that is usable in actual play.
	
	softBootsEquip.lua - equipping soft boots at low mana

	** DO NOT EDIT THIS FILE. INSTEAD, COPY IT TO
	"Documents\XenoBot\Scripts" AND EDIT THE COPY. **
]]--


--set the name or ID of the normal boots
local normalBoots = "boots of haste"
local equipMana = 2500
local removeMana = 2900

-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------

--this decides whether we have an id or a name, converting names into ids
local normalBootsId = Item.GetItemIDFromDualInput(normalBoots)

--this continuously loops, executing the code inside over and over again
while (true) do
	--this checks if our mana is low, and if we aren't wearing soft boots
    if (Self.Mana() <= equipMana and Self.Feet().id ~= 3549) then
		--equips the soft boots
        Self.Equip(6529, "feet")
    --this checks, if the previous check fails, if we have enough mana and still have softs on
    elseif (Self.Mana() >= removeMana and Self.Feet().id ~= normalBootsId) then
		--this equips normal boots again
        Self.Equip(normalBootsId, "feet")
    end
   
    --this causes the loop to wait between 1.5 and 2.5 seconds before retrying
    wait(1500, 2500)
end
